---
title: "Group 25 Assignment 7"
format: html
editor: visual
---

## Background

## Load and Clean Data

First we load the data and the necessary libraries to perform a PCA

```{r}

library(tidyverse)
library(broom)  # devtools::install_github("tidymodels/broom")
library(cowplot)

biopsy <- read_csv("https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
```

From the biopsy data set we can create a new data set that is appropriate to perform PCA analysis:

```{r}
PCA_dataset <- biopsy |> 
  select(-outcome) |> 
  prcomp(scale = TRUE)
```

```{r}
Biopsy_Data_with_PCAcomponents <- PCA_dataset |> 
  augment(biopsy) 
  
```

## Data Analysis

Creating scatter plot of the two first fitted PCA columns.

```{r}
Biopsy_Data_with_PCAcomponents |>
  select(.fittedPC1, .fittedPC2, outcome) |>  
  ggplot(aes(x = .fittedPC1, 
             y = .fittedPC2, 
             color = outcome)) +  
  geom_point() + 
  ggtitle('Scatter plot of PCA 1 and PCA 2') +
  scale_color_manual(
    values = c(malignant = "purple", benign = "darkblue"))  # Correct closing parenthesis

```
